name: CI Pull Request Open
on:
  pull_request:
jobs:
  image:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: "-Xmx1500m -XX:+HeapDumpOnOutOfMemoryError"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - name: Setup Java
        uses: action/setup-java@v4
        with:
          java-version: 21
          java-distribution: oracle
          cache: maven
      - run: mvn --version
      - name: Build with Maven
        run: mvn -s maven-settings.xml clean install surefire-report:report pmd:cpd pmd:pmd spotbugs:spotbugs -B -e -DskipTests -Pnative
      - name: Test with Maven
        run: > 
          mvn -s maven-settings.xml verify -B -e -DrerunFailingTestsCount=2
              -Dmaven.test.failure.ignore=true -Dansi.strip=true -Pnative
      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
