name: On PR Open or Push Do Build and Test
on:
  pull_request:
  push:
    branches:
      - main
      - 15.[0-9]+.x
      - 14.0.x
jobs:
  ci-build-test-pr:
    name: Maven Build and Test
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: "-Xmx1500m -XX:+HeapDumpOnOutOfMemoryError"
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: ./mvnw --version

      - name: Maven build
        if: (github.event_name == 'pull_request') && !contains(github.event.pull_request.labels.*.name, 'Image Required')
        run: >
            ./mvnw clean install -s maven-settings.xml -B -e -DskipTests -Pnative

      - name: Maven build Distribution
        if: (github.event_name != 'pull_request') || contains(github.event.pull_request.labels.*.name, 'Image Required')
        run: >
            ./mvnw clean install -s maven-settings.xml -B -e -DskipTests -Pnative -Pdistribution

      - name: Server artifact
        if: (github.event_name != 'pull_request') || contains(github.event.pull_request.labels.*.name, 'Image Required')
        uses: actions/upload-artifact@v4
        with:
          name: infinispan-server
          compression-level: 0
          path: |
            distribution/target/distribution/infinispan-server-*.zip

#      - name: Maven Test
#        run: >
#            ./mvnw verify -s maven-settings.xml -B -e -DrerunFailingTestsCount=2
#            -Dmaven.test.failure.ignore=true -Dansi.strip=true -Pnative
#
#      - name: Archive commit sha PR
#        if: >
#          (success() || failure()) &&
#          github.event_name == 'pull_request'
#        run: |
#           echo -n ${{ github.event.pull_request.head.sha }} > github-sha.txt
#
#      - name: Archive commit sha push
#        if: >
#          (success() || failure()) &&
#          github.event_name == 'push'
#        run: |
#           echo -n $GITHUB_SHA > github-sha.txt
#
#      - name: Archive surefire test report
#        if: (success() || failure())
#        uses: actions/upload-artifact@v4
#        with:
#          name: surefire-test-report
#          path: |
#            **/surefire-reports/TEST-*.xml
#            **/*.dump*
#            **/hs_err_*
#            github-sha.txt
#            !**/target/*-reports*/**/TEST-*FLAKY.xml
#
## Create artifact with branch name and surefile flaky test report
#      - name: Check flaky report existence
#        if: success() || failure()
#        id: check_flaky_report
#        uses: andstor/file-existence-action@v3
#        with:
#          files: "**/target/*-reports*/**/TEST-*FLAKY.xml"
#
#      - name: Archive base_ref
#        if: (success() || failure()) && steps.check_flaky_report.outputs.files_exists == 'true'
#        env:
#          TARGET_BRANCH: ${{ github.base_ref }}
#          EVENT_NAME: ${{ github.event_name }}
#          EVENT_NUMBER: ${{ github.event.number }}
#        run: |
#          echo -n $TARGET_BRANCH > target-branch.txt
#          echo -n $EVENT_NAME > event-name.txt
#          echo -n $EVENT_NUMBER > event-number.txt
#
#      - name: Archive flaky test report
#        if: (success() || failure()) && steps.check_flaky_report.outputs.files_exists == 'true'
#        uses: actions/upload-artifact@v4
#        with:
#          name: flaky-test-report
#          path: |
#            **/target/*-reports*/**/TEST-*FLAKY.xml
#            target-branch.txt
#            event_name.txt
#            event_number.txt
