name: Publish Test Report
run-name: ${{ github.event.workflow_run.display_title }}
on:
   workflow_run:
     workflows: [Test]
     types: [completed]
   # Rerun report publishing on exising test run
jobs:
   publish:
      name: Publish Surefire Report
      runs-on: ubuntu-latest
      steps:
# Downloading surefire report artifact containing
# zip file with reports and file
# containing commit sha
        - name: Set run_id based on event type
          id: run_id
          run: |
            echo "runid=${{ github.event.workflow_run.id }}" >> $GITHUB_OUTPUT

        - name: Download a Build Artifact
          uses: actions/download-artifact@v4.2.1
          with:
            name: surefire-test-report
            github-token: ${{ github.token }}
            run-id: ${{ steps.run_id.outputs.runid }}

        - name: Get github sha
          id: github_sha
          uses: juliangruber/read-file-action@v1
          with:
            path: ./github-sha.txt

        - uses: actions/create-github-app-token@v2
          id: app-token
          with:
            # required
            app-id: ${{ secrets.GH_APP_ISPN_ID }}
            private-key: ${{ secrets.GH_APP_ISPN_KEY }}

        - name: Get job status
          env:
            GH_TOKEN: ${{ steps.app-token.outputs.token }}
          id: job-status
          run: |
            JOB_STATUS=$(gh api https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ steps.run_id.outputs.runid }}/jobs --jq '.jobs[] | select(.name=="Maven Test") | .conclusion')
            echo "job_status=$JOB_STATUS" >> $GITHUB_OUTPUT

        - name: Publish Test Report
          if: (success() || failure()) && steps.job-status.outputs.job_status == 'success'
          # Waiting for https://github.com/ScaCap/action-surefire-report/pull/251
          uses: rigazilla/action-surefire-report@summary
          with:
            github_token: ${{ steps.app-token.outputs.token }}
            check_name: Test Report Result
            commit: ${{ steps.github_sha.outputs.content }}
            ignore_flaky_tests: true
            summary: "Result from workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ steps.run_id.outputs.runid }}"
            report_paths: |
              **/*-reports*/**/TEST-*.xml

        - name: Install xmlstarlet tool
          shell: bash
          run: |
             sudo apt-get update
             sudo apt-get install -y xmlstarlet

        - name: Check test number
          if: success() || failure()
          id: test-number
          env:
            MIN_TEST_NUM: 35000
            GH_TOKEN: ${{ github.token }}
          run: |
            COUNT=$(find . -name "TEST-*.xml" | grep -v polarion | while read f; do xmlstarlet sel -t -c  "count(//testcase)" -n "$f"; done | awk '{s+=$1} END {print s}')
            echo "test_count=$COUNT" >> $GITHUB_OUTPUT
            echo "test_min=$MIN_TEST_NUM" >> $GITHUB_OUTPUT

   db:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dbs:
          - mssql
          - oracle
          - db2
    steps:
    - name: Set run_id based on event type
      id: run_id
      run: |
         echo "runid=${{ github.event.workflow_run.id }}" >> $GITHUB_OUTPUT

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.2.1
      with:
        name: surefire-test-report-${{ matrix.dbs }}
        github-token: ${{ github.token }}
        run-id: ${{ steps.run_id.outputs.runid }}

    - name: Get github sha
      id: github_sha
      uses: juliangruber/read-file-action@v1
      with:
        path: ./github-sha.txt

    - uses: actions/create-github-app-token@v2
      id: app-token
      with:
        # required
        app-id: ${{ secrets.GH_APP_ISPN_ID }}
        private-key: ${{ secrets.GH_APP_ISPN_KEY }}

    - name: Get job status
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      id: job-status
      run: |
        JOB_STATUS=$(gh api https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ steps.run_id.outputs.runid }}/jobs --jq '.jobs[] | select(.name=="db (${{ matrix.dbs }})") | .conclusion')
        echo "job_status=$JOB_STATUS" >> $GITHUB_OUTPUT

    - name: Publish Test Report
      if: (success() || failure()) && steps.job-status.outputs.job_status == 'success'
      # Waiting for https://github.com/ScaCap/action-surefire-report/pull/251
      uses: rigazilla/action-surefire-report@summary
      with:
        github_token: ${{ steps.app-token.outputs.token }}
        check_name: Test Report Result ${{ matrix.dbs }}
        commit: ${{ steps.github_sha.outputs.content }}
        ignore_flaky_tests: true
        summary: "Result from workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ steps.run_id.outputs.runid }}"
        report_paths: |
          **/*-reports*/**/TEST-*.xml
