name: Publish Test Report
run-name: ${{ github.event.workflow_run.display_title }}
on:
   workflow_run:
     workflows: [Test]
     types: [completed]
   # Rerun report publishing on exising test run
jobs:
   publish:
      name: Publish Surefire Report
      runs-on: ubuntu-latest
      steps:
        - name: Set run_id based on event type
          id: run_id
          run: |
            echo "runid=${{ github.event.workflow_run.id }}" >> "$GITHUB_OUTPUT"

        # Downloading surefire report artifact containing
        - name: Download Surefire Report Artifact
          uses: actions/download-artifact@v7.0.0
          with:
            pattern: surefire-test-report*
            github-token: ${{ github.token }}
            run-id: ${{ steps.run_id.outputs.runid }}

        # Downloading github-sha.txt file
        - name: Get github sha
          id: github_sha
          uses: juliangruber/read-file-action@v1
          with:
            path: ./surefire-test-report/github-sha.txt

        # Get GitHub App token to use in API calls
        - uses: actions/create-github-app-token@v2
          id: app-token
          with:
            # required
            app-id: ${{ secrets.GH_APP_ISPN_ID }}
            private-key: ${{ secrets.GH_APP_ISPN_KEY }}

        # Get job status, next steps will be executed only if test job was successful
        - name: Get job status
          env:
            GH_TOKEN: ${{ steps.app-token.outputs.token }}
          id: job-status
          run: |
            JOB_STATUS=$(gh api https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ steps.run_id.outputs.runid }}/jobs --jq '.jobs[] | select(.name=="Maven Test") | .conclusion')
            echo "job_status=$JOB_STATUS" >> "$GITHUB_OUTPUT"

        - name: Download Check Run ID
          if: (success() || failure()) && steps.job-status.outputs.job_status == 'success'
          uses: actions/download-artifact@v7.0.0
          with:
            name: check-run-id
            github-token: ${{ github.token }}
            run-id: ${{ steps.run_id.outputs.runid }}

        - name: Read Check Run ID
          if: (success() || failure()) && steps.job-status.outputs.job_status == 'success'
          id: read_check_id
          run: |
            CHECK_RUN_ID=$(cat check-run-id.txt)
            echo "check_run_id=$CHECK_RUN_ID" >> "$GITHUB_OUTPUT"

        - name: Publish Test Report
          if: (success() || failure()) && steps.job-status.outputs.job_status == 'success'
          # Waiting for https://github.com/ScaCap/action-surefire-report/pull/251
          uses: rigazilla/action-surefire-report@summary
          with:
            github_token: ${{ steps.app-token.outputs.token }}
            check_name: Test Report Result
            commit: ${{ steps.github_sha.outputs.content }}
            ignore_flaky_tests: true
            summary: "Result from workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ steps.run_id.outputs.runid }}"
            report_paths: |
              **/surefire-test-report/**/*-reports*/**/TEST-*.xml

        - name: Display Check Run URL
          if: (success() || failure()) && steps.job-status.outputs.job_status == 'success'
          run: |
            echo "::notice title=Test Report Published::View test report: https://github.com/${{ github.repository }}/runs/${{ steps.read_check_id.outputs.check_run_id }}"

        - name: Set failure check if Publish Test Report step failed
          if: failure() && steps.job-status.outputs.job_status == 'success'
          env:
            GH_TOKEN: ${{ steps.app-token.outputs.token }}
          run: |
            gh api repos/${{ github.repository }}/check-runs/"${{ steps.read_check_id.outputs.check_run_id }}"\
              -H "Accept: application/vnd.github+json" \
              -f status="completed" \
              -f conclusion="failure" \
              -f "output[summary]=Result from workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
              -f "output[title]=Run Failed" \
              --method PATCH

        - name: Install xmlstarlet tool
          shell: bash
          if: steps.job-status.outputs.job_status == 'success'
          run: |
             sudo apt-get update
             sudo apt-get install -y xmlstarlet

        - name: Check test number
          id: test-number
          env:
            MIN_TEST_NUM: 32300
            GH_TOKEN: ${{ github.token }}
          run: |
            if [ "${{ steps.job-status.outputs.job_status }}" != "success" ]; then
              echo "Job status is '${{ steps.job-status.outputs.job_status }}', marking as failed."
              exit 1
            fi
            COUNT=$(find . -name "TEST-*.xml" | while read -r f; do xmlstarlet sel -t -c  "count(//testcase)" -n "$f"; done | awk '{s+=$1} END {print s}')
            {
              echo "test_count=$COUNT"
              echo "test_min=$MIN_TEST_NUM"
              echo "is_valid=true"
            } >> "$GITHUB_OUTPUT"

        - name: Set test number check status on success
          if: fromJSON(steps.test-number.outputs.test_count) >= fromJSON(steps.test-number.outputs.test_min)
          uses: myrotvorets/set-commit-status-action@v2.0.1
          with:
            status: success
            sha: ${{ steps.github_sha.outputs.content }}
            context: Tests number check
            description: Success. ${{ steps.test-number.outputs.test_count }} test ran, minimum required is ${{ steps.test-number.outputs.test_min }}
            targetUrl: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

        - name: Set test number check status if failed
          if: fromJSON(steps.test-number.outputs.test_count) < fromJSON(steps.test-number.outputs.test_min)
          uses: myrotvorets/set-commit-status-action@v2.0.1
          with:
            status: failure
            sha: ${{ steps.github_sha.outputs.content }}
            context: Tests number check
            description: Fail. ${{ steps.test-number.outputs.test_count }} test ran, minimum required is ${{ steps.test-number.outputs.test_min }}
            targetUrl: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

   targets-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targets:
          - mssql
          - oracle
          - db2
          - tomcat
          - rolling-upgrades
    steps:
    - name: Set run_id based on event type
      id: run_id
      run: |
         echo "runid=${{ github.event.workflow_run.id }}" >> "$GITHUB_OUTPUT"

    - name: Download a Build Artifact
      uses: actions/download-artifact@v7.0.0
      with:
        name: surefire-test-report-${{ matrix.targets }}
        github-token: ${{ github.token }}
        run-id: ${{ steps.run_id.outputs.runid }}

    - name: Get github sha
      id: github_sha
      uses: juliangruber/read-file-action@v1
      with:
        path: ./github-sha.txt

    - uses: actions/create-github-app-token@v2
      id: app-token
      with:
        # required
        app-id: ${{ secrets.GH_APP_ISPN_ID }}
        private-key: ${{ secrets.GH_APP_ISPN_KEY }}

    - name: Get job status
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      id: job-status
      run: |
        if [ "${{ matrix.targets }}" = "tomcat" ]; then
          JOB_NAME="tomcat"
        elif [ "${{ matrix.targets }}" = "rolling-upgrades" ]; then
          JOB_NAME="rolling-upgrades"
        else
          JOB_NAME="db (${{ matrix.targets }})"
        fi

        JOB_STATUS=$(gh api "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ steps.run_id.outputs.runid }}/jobs" --jq ".jobs[] | select(.name==\"$JOB_NAME\") | .conclusion")
        echo "job_status=$JOB_STATUS" >> "$GITHUB_OUTPUT"

    - name: Download Check Run ID
      if: (success() || failure()) && steps.job-status.outputs.job_status == 'success'
      uses: actions/download-artifact@v7.0.0
      with:
        name: check-run-id-${{ matrix.targets }}
        github-token: ${{ github.token }}
        run-id: ${{ steps.run_id.outputs.runid }}

    - name: Read Check Run ID
      if: (success() || failure()) && steps.job-status.outputs.job_status == 'success'
      id: read_check_id
      run: |
        CHECK_RUN_ID=$(cat "check-run-id-${{ matrix.targets }}.txt")
        echo "check_run_id=$CHECK_RUN_ID" >> "$GITHUB_OUTPUT"

    - name: Publish Test Report
      if: (success() || failure()) && steps.job-status.outputs.job_status == 'success'
      # Waiting for https://github.com/ScaCap/action-surefire-report/pull/251
      uses: rigazilla/action-surefire-report@summary
      with:
        github_token: ${{ steps.app-token.outputs.token }}
        check_name: Test Report Result ${{ matrix.targets }}
        commit: ${{ steps.github_sha.outputs.content }}
        ignore_flaky_tests: true
        summary: "Result from workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ steps.run_id.outputs.runid }}"
        report_paths: |
          **/*-reports*/**/TEST-*.xml

    - name: Display Check Run URL
      if: (success() || failure()) && steps.job-status.outputs.job_status == 'success'
      run: |
        echo "::notice title=Test Report Published (${{ matrix.targets }})::View test report: https://github.com/${{ github.repository }}/runs/${{ steps.read_check_id.outputs.check_run_id }}"

    - name: Set failure check if Publish Test Report step failed
      if: failure()
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      run: |
        gh api repos/${{ github.repository }}/check-runs/"${{ steps.read_check_id.outputs.check_run_id }}" \
          -H "Accept: application/vnd.github+json" \
          -f status="completed" \
          -f conclusion="failure" \
          -f "output[summary]=Result from workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          -f "output[title]=Run Failed" \
          --method PATCH
