name: On Test Publish Surefire Report
on:
   workflow_run:
     workflows: [On Build Do Test]
     types: [completed]
jobs:
   publish:
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      name: Publish Surefire Report
      runs-on: ubuntu-latest
      steps:
        - name: Install xmlstarlet tool
          shell: bash
          run: |
             sudo apt-get update
             sudo apt-get install -y xmlstarlet

# Downloading surefire report artifact containing
# zip file with reports and file
# containing commit sha
        - name: Download artifact
          id: download-artifact
          uses: actions/github-script@v7
          with:
            result-encoding: string
            script: |
              let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 run_id: context.payload.workflow_run.id,
              });
              let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
                return artifact.name == "surefire-test-report"
              })[0];
              if (typeof matchArtifact == 'undefined') {
               // No surefire report artifact found
               return "No Report";
              }
              let download = await github.rest.actions.downloadArtifact({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 artifact_id: matchArtifact.id,
                 archive_format: 'zip',
              });
              let fs = require('fs');
              fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/surefire-test-report.zip`, Buffer.from(download.data));
              return "Report Found";

        - if: steps.download-artifact.outputs.result == 'Report Found'
          name: Unzip artifact
          run: unzip surefire-test-report.zip

        - name: Get github sha
          id: github_sha
          uses: juliangruber/read-file-action@v1
          with:
            path: ./github-sha.txt

        - name: Remove flaky tests from failure report
          if: (success() || failure())
          run: |
               find . -name "TEST-*Test.xml" | while read f
                   do
                      xmlstarlet ed --inplace -d "//testcase[flakyFailure]" $f
                   done
        - name: Publish Test Report
          if: success() || failure()
          uses: ScaCap/action-surefire-report@v1
          with:
            commit: ${{ steps.github_sha.outputs.content }}
            check_name: check-ci test report
            report_paths: |
              **/surefire-reports/TEST-*.xml

        - name: Check test number
          if: success() || failure()
          env:
            MIN_TEST_NUM: 30000
            GH_TOKEN: ${{ github.token }}
          run: |
            COUNT=$(find . -name "TEST-*.xml" | while read f; do xmlstarlet sel -t -c  "count(//testcase)" -n "$f"; done | awk '{s+=$1} END {print s}')
            if [ "$COUNT" -lt "$MIN_TEST_NUM" ]; then
               gh api -X POST -H "Accept: application/vnd.github+json" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  -f 'name=Check number tests ran' \
                  -f 'head_sha=${{ steps.github_sha.outputs.content }}' \
                  -f 'status=completed' \
                  -f 'conclusion=failure' \
                  -f 'output[title]=Check number tests ran' \
                  -f "output[summary]=Fail. $COUNT test ran, minimum required is $MIN_TEST_NUM" \
                     /repos/${{ github.repository }}/check-runs
            fi
