name: Operator Upgrade Tests

on:
  push:
    branches:
      - main
      - '*.0.x'
  pull_request:
    branches:
      - main
      - '*.0.x'

concurrency:
  # Cancel jobs same head_branch same repo, works
  # both for pull_request and push
  group: >
      ${{ github.workflow }}-${{ github.repository }}-
      ${{ github.event.pull_request.head.ref || github.event.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  image:
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.infinispan.outputs.image }}
      version: ${{ steps.infinispan.outputs.version }}

    steps:
      - uses: actions/checkout@v5

      - name: Setup Java
        uses: ./.github/actions/setup-java

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        id: infinispan
        run: |
          SERVER_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          OPERAND_VERSION=$(echo ${SERVER_VERSION} | cut -d '-' -f 1)
          IMAGE="localhost:5001/server:${SERVER_VERSION}"

          ./mvnw install -DskipTests -am -pl server/runtime,server/image -Pimage -Dimage.name=${IMAGE}
          docker save ${IMAGE} > /tmp/operand-image.tar

          echo "image=${IMAGE}" >> ${GITHUB_OUTPUT}
          echo "version=${OPERAND_VERSION}" >> ${GITHUB_OUTPUT}

      - name: Upload
        uses: actions/upload-artifact@v5
        with:
          name: operand-image
          path: /tmp/operand-image.tar

  tests:
    needs: image
    uses: infinispan/infinispan-operator/.github/workflows/test_upgrades.yml@main
    with:
      operand: ${{ needs.image.outputs.image }}
      operandArtifact: operand-image
      operandVersion: ${{ needs.image.outputs.version }}
      ref: main
      repository: infinispan/infinispan-operator
      skipList: '15.1.0,15.1.1'
      testName: TestOperandUpgrades
      upgradeDepth: 0
