name: Release Images

on:
  workflow_call:
    inputs:
      version:
        description: 'Infinispan Server version'
        required: true
        type: string
      branch:
        description: 'The repository branch to checkout'
        required: true
        type: string
      type:
        description: 'The type of release (latest, prerelease)'
        required: true
        type: string
      push:
        description: 'Push to remote repositories'
        default: true
        type: boolean
  workflow_dispatch:
    inputs:
      version:
        description: 'Infinispan Server version'
        required: true
        type: string
      branch:
        description: 'The repository branch to checkout'
        default: main
        type: string
      type:
        description: The type of release
        required: true
        default: default
        type: choice
        options:
          - default
          - latest
          - prerelease
      push:
        description: 'Push to remote repositories'
        default: true
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.branch }}

      -  name: Generate Image Tags
         run: echo "IMAGE_TAGS=$(./.github/scripts/image_tags.sh)" >> "$GITHUB_ENV"
         env:
            VERSION: ${{ inputs.version }}
            TYPE: ${{ inputs.type }}

      - name: Log in to Docker Hub
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: docker.io

      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
          registry: quay.io

      - name: Install qemu
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          build-args: |
            BRAND_VERSION=${{ inputs.version }}
            BRAND_NAME=Infinispan
            JDK_DIST=src/main/docker/adoptium
            SERVER_DIST=https://github.com/infinispan/infinispan/releases/download/${{ inputs.version }}/infinispan-server-${{ inputs.version }}.zip
          containerfiles: ./server/image/src/main/docker/Dockerfile
          context: ./server/image
          image: server
          platforms: linux/amd64, linux/arm64
          tags: ${{ env.IMAGE_TAGS }}

      - name: Push to Docker Hub
        id: push-to-docker
        if: ${{ inputs.push }}
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: docker.io/infinispan
          image: server
          tags: ${{ steps.build-image.outputs.tags }}

      - name: Print Docker Hub image url
        run: echo "Image pushed to ${{ steps.push-to-docker.outputs.registry-paths }}"

      - name: Push to Quay.io
        id: push-to-quay
        if: ${{ inputs.push }}
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: quay.io/infinispan
          image: server
          tags: ${{ steps.build-image.outputs.tags }}

      - name: Print Quay.io image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
