name: Resume Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The Infinispan branch to checkout when cutting the release."
        required: true
        default: "main"
      version:
        description: "Release version"
        required: true
      type:
        type: choice
        description: The type of release
        required: true
        default: "default"
        options:
          - default
          - latest
          - prerelease


jobs:
  published:
    runs-on: ubuntu-latest
    steps:
      - uses: gerdemann/http-status-code@1.1.1
        with:
          url: https://repo1.maven.org/maven2/org/infinispan/infinispan-distribution/${{ github.event.inputs.version }}/infinispan-distribution-${{ github.event.inputs.version }}.pom
          code: 200
          timeout: 10800000
          interval: 10000

  native-cli:
    needs: published
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2022, ubuntu-24.04-arm]
        include:
          - os: ubuntu-latest
            asset_name: linux-x86_64
            gu_binary: gu
          - os: macos-latest
            asset_name: osx-aarch_64
            gu_binary: gu
          - os: windows-2022
            asset_name: windows-x86_64
            gu_binary: gu.cmd
          - os: ubuntu-24.04-arm
            asset_name: linux-aarch_64
            gu_binary: gu
    steps:
      - uses: actions/checkout@v5

      - if: ${{ matrix.os == 'windows-2022' }}
        name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2.0.0

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Release Tag
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.version }}

      - if: ${{ matrix.os == 'windows-2022' }}
        name: Build native executable
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
          mvnw.cmd package -Pdistribution -Pwindows -Pnative -am -pl quarkus/cli
        shell: cmd

      - if: ${{ matrix.os != 'windows-2022' }}
        name: Build native executable
        run: ./mvnw package -Pdistribution -Pnative -am -pl quarkus/cli

      - name: Upload CLI native executable
        id: upload-cli-native-executable
        run: |
          gh release upload ${{ github.event.inputs.version }} quarkus/cli/target/infinispan-cli-${{ github.event.inputs.version }}-${{ matrix.asset_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.INFINISPAN_RELEASE_TOKEN }}

  images:
    needs: published
    uses: ./.github/workflows/release_image.yml
    secrets: inherit
    with:
      branch: ${{ inputs.branch }}
      version: ${{ inputs.version }}
      type: ${{ inputs.type }}

  operator:
    needs: images
    if: contains(github.event.inputs.version, '.Final')
    uses: infinispan/infinispan-operator/.github/workflows/add_operand.yml@main
    secrets: inherit
    with:
      image: quay.io/infinispan/server:${{ github.ref_name }}
      ref: main
      repository: infinispan/infinispan-operator
